name: CI Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Build and Test
        run: |
          mvn clean package
          mvn test
      - name: Upload Test Report
        uses: actions/upload-artifact@v4  
        if: always()
        with:
          name: test-reports
          path: target/surefire-reports/
