name: CI Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'
      - name: Build and Test
        run: |
          mvn clean package
          mvn test
      - name: Upload Test Report
        uses: actions/upload-artifact@v4  
        if: always()
        with:
          name: test-reports
          path: target/surefire-reports/

  smoke-tests:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Run Smoke Tests
        run: mvn test -Dgroups=smoke

      - name: Upload Smoke Test Report
        uses: actions/upload-artifact@v4  
        if: always()
        with:
          name: smoke-test-reports
          path: target/surefire-reports/

